### ISSUE TITLE
How to run ./deploy.sh as in getting python version error

### ISSUE THREAD

**Issue by pradeepsinghai** [doitintl/iris3#12]
Hi,
When running ./deploy.sh in google cloud shell. I'm getting below error
"This script requires Python 3.8 or higher!
You are using Python 3.7."

How to update cloud shell to 3.7 or I have to run this script somewhere else?

**Comment by JoshuaFox** [comment]
Hello,
 [Iris3 code](https://github.com/doitintl/iris3/blob/c4250cd88f8e146d15472d1ac289fe5f52942e77/util/check_version.py) uses some Python 3.8 features and so requires that.

I have been using my laptop rather than CloudShell, as CloudShell is ephemeral, but you could still do that.  

Pyenv is one option : https://stackoverflow.com/a/57403582/39242
Or building   Python3.8  as follows (replace 3.7 with 3.8) https://stackoverflow.com/a/54347468/39242

**Comment by JoshuaFox** [comment]
Closing this given the solution above
